In [1]:
# Numerical Computing with Python and Numpy

In [2]:
!pip install numpy


In [3]:
import numpy as np

In [4]:
# We are using climate data and weights here to find out the yield (tons per hactore) of apples in certain area (kanto).
# climate data -> ave temperature (farenheit), rainfall (mm) and ave relative humidity (%).
# weights -> w1, w2, w3.
# yield_of_apples = w1*tempetrature + w2*rainfall + w3*humidity

In [5]:
kanto =np.array([72, 63, 47])

In [6]:
kanto

array([72, 63, 47])

In [7]:
weights = np.array([0.2, 0.3, 0.4])

In [8]:
weights

array([0.2, 0.3, 0.4])

In [9]:
type(kanto)

numpy.ndarray

In [10]:
weights[1]

0.3

In [11]:
np.dot(kanto, weights)

52.099999999999994

In [12]:
kanto * weights

array([14.4, 18.9, 18.8])

In [13]:
(kanto * weights).sum()

52.099999999999994

In [14]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np =np.array(arr1)
arr2_np =np.array(arr2)

In [15]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: total: 93.8 ms
Wall time: 117 ms


833332333333500000

In [16]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np =np.array(arr1)
arr2_np =np.array(arr2)

In [17]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 433 µs


-1942957984

In [18]:
weights

array([0.2, 0.3, 0.4])

In [19]:
weights.dtype

dtype('float64')

In [20]:
# Multi-dimentional Numpy arrays
climate_data = np.array([[73, 67, 43],
                        [91, 88, 64],
                        [87, 134, 58],
                        [102, 43, 37],
                        [69, 96, 70]])


In [21]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [22]:
# 2D array (matrix)
climate_data.shape

(5, 3)

In [23]:
# 1D array (vector)
weights.shape

(3,)

In [24]:
# 3D array
arr3 = np.array ([
    [[11, 12, 13],
    [13, 14, 15]],
    [[15, 16, 17],
    [17, 18, 19.5]]
])

In [25]:
arr3.shape

(2, 2, 3)

In [26]:
# Matrix multiplication
np.matmul(climate_data, weights)

array([51.9, 70.2, 80.8, 48.1, 70.6])

In [27]:
climate_data @ weights

array([51.9, 70.2, 80.8, 48.1, 70.6])

In [28]:
import urllib.request
'''
urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')
'''

"\nurllib.request.urlretrieve(\n    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', \n    'climate.txt')\n"

In [29]:
climate_data =np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [30]:
climate_data # temperature, rainfall, humidity 

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [31]:
climate_data.shape

(10000, 3)

In [32]:
weights = np.array([0.3, 0.2, 0.5])

In [33]:
yields = climate_data @ weights

In [34]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [35]:
yields.shape

(10000,)

In [36]:
# Add the yields back to clomate_data as a forth column using the np.concatenate function (joining two arrays)

In [37]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [38]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [39]:
# save the climate_result file
np.savetxt('climate_results.txt',
          climate_results,
          fmt='%.2f',
          header='temperature,rainfall,humidity,yield_apples',
          comments='')

In [40]:
# Arithmetic operations and broadcasting

In [41]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,1,2,3]])

In [42]:
arr3 = np.array([[11,12,13,14],
                [15,16,17,18],
                [19,11,12,13]])

In [43]:
# Adding a scalar
arr2 + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14,  6,  7,  8]])

In [44]:
# Element-wise subtraction
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [45]:
# Division by scalar
arr2/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [46]:
# Element-wise multiplication
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [47]:
# Modulas with scalar
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

In [48]:
# Broadcasting with compatible shape
arr4 = np.array([4, 5, 6, 7])

In [49]:
arr4.shape

(4,)

In [50]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [51]:
# Comparision
arr2 == arr3

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [52]:
arr2 <= arr3

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
arr3 !=arr2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [54]:
(arr2 == arr3).dtype

dtype('bool')

In [55]:
# Number of matching elements in arrays
(arr2 == arr3).sum()

0

In [56]:
# Array Indexing and Slicing

In [57]:
arr5 = np.array([
    [[11, 12, 13, 14],
    [13, 14, 15, 19]],
    
    [[15, 16, 17, 21],
    [63, 92, 36, 18]],
    
    [[98, 32, 81, 23],
    [17, 18, 19.5, 43]]
])

In [58]:
arr5.shape

(3, 2, 4)

In [59]:
# Accessing to single element in the array
arr5[1, 1, 2]

36.0

In [60]:
arr5[1, 1, 2]

36.0

In [61]:
# Subarray using ranges
arr5[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [62]:
arr5

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. , 19. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [63]:
# Mixing indices and ranges
arr5[1:, 1, 3]

array([18., 43.])

In [64]:
# Other ways of creating Numpy arrays

In [65]:
# All zeros
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [66]:
# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [67]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
# Random vector
np.random.rand(7)

array([0.90031712, 0.88853379, 0.89633421, 0.234706  , 0.89970078,
       0.64890117, 0.86788911])

In [69]:
# Random matrix
np.random.randn(3, 4, 3)

array([[[-1.18404413, -0.07779081,  0.8084871 ],
        [-1.04847419, -0.31850161,  1.04504508],
        [ 0.6128878 , -0.84600091, -0.3210091 ],
        [-0.79963631, -0.46517546,  0.07775967]],

       [[ 0.32416349, -1.06452682,  2.96065668],
        [-0.75529296, -0.23779407, -0.61894293],
        [ 0.46171567, -0.26652042, -0.24722437],
        [ 0.51026631,  0.50134017,  1.01634463]],

       [[ 1.02940085,  1.55357572, -1.72974058],
        [ 0.88339232,  0.17032752,  0.75029817],
        [ 1.70306546, -0.10066488,  0.73838678],
        [ 2.21081068, -1.88705981, -1.44158042]]])

In [70]:
# Array with fixed value
np.full([2,3], 19)

array([[19, 19, 19],
       [19, 19, 19]])

In [71]:
# Range with start, end and step
np.arange(9, 90, 3)

array([ 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57,
       60, 63, 66, 69, 72, 75, 78, 81, 84, 87])

In [72]:
np.arange(9, 90, 3).reshape(3,3,3)

array([[[ 9, 12, 15],
        [18, 21, 24],
        [27, 30, 33]],

       [[36, 39, 42],
        [45, 48, 51],
        [54, 57, 60]],

       [[63, 66, 69],
        [72, 75, 78],
        [81, 84, 87]]])

In [73]:
# Equally spaced numbers in a range
np.linspace(3, 27, 18)

array([ 3.        ,  4.41176471,  5.82352941,  7.23529412,  8.64705882,
       10.05882353, 11.47058824, 12.88235294, 14.29411765, 15.70588235,
       17.11764706, 18.52941176, 19.94117647, 21.35294118, 22.76470588,
       24.17647059, 25.58823529, 27.        ])

In [74]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [75]:
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [76]:
print(a2D)

[[1 2]
 [3 4]]
