In [1]:
# Python - Mathametics

In [2]:
# Importing libraries
import numpy as np

In [3]:
# Declaring scalers
s = 7

In [4]:
s

7

In [5]:
# Declaring Vectors
v = np.array([7,4,-8])

In [6]:
v

array([ 7,  4, -8])

In [7]:
# Declaring Matrices

In [8]:
m = np.array([[3,17,2],[0,-5,13]])

In [9]:
m

array([[ 3, 17,  2],
       [ 0, -5, 13]])

In [10]:
# Data types and data shapes
type(s)

int

In [11]:
type(v)

numpy.ndarray

In [12]:
type(m)

numpy.ndarray

In [13]:
x_array = np.array([10])

In [14]:
type(x_array)

numpy.ndarray

In [15]:
m.shape

(2, 3)

In [16]:
v.shape

(3,)

In [17]:
x_array.shape

(1,)

In [18]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [19]:
# Creating a column vector
v.reshape(1,3)

array([[ 7,  4, -8]])

In [20]:
v.reshape(3,1)

array([[ 7],
       [ 4],
       [-8]])

In [21]:
m+s

array([[10, 24,  9],
       [ 7,  2, 20]])

In [ ]:
m+x_array

In [ ]:
v+s

In [ ]:
v

In [ ]:
v+x_array

In [ ]:
m+v

In [ ]:
# Creating Tensor
m1 = np.array([[3,17,-2],[-5,6,11]])
m1

In [ ]:
m2 = np.array([[3,8,1],[2,7,-5]])
m2

In [ ]:
t = np.array([m1,m2])

In [ ]:
t

In [ ]:
# Checking shape
t.shape

In [ ]:
# Adding and Subtracting matrices (matrices should be matchable)
m1 = np.array([[5,12,6],[-3,0,14]])
m1

In [ ]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

In [ ]:
m1 + m2

In [ ]:
m1 - m2

In [ ]:
# Adding and Subtracting vectors
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [ ]:
v1 + v2

In [ ]:
v1 - v2

In [ ]:
# Exception (addition and subtracting with a scalar)
m1

In [ ]:
m1 +1

In [ ]:
v1

In [ ]:
v1- 1

In [ ]:
m1 + np.array([1])

In [ ]:
v1 - np.array([2])

In [ ]:
# Transposing matrices
A = np.array([[9,17,6],[0,10,-4]])
A

In [ ]:
A.T

In [ ]:
# Transposing scalars
s = np.array([17])

In [ ]:
s

In [ ]:
# Transposing vectors
a = np.array([1,2,3])
a

In [ ]:
a.T

In [ ]:
a.shape

In [ ]:
a_reshaped = a.reshape(1,3)
a_reshaped

In [ ]:
a_reshaped.T

In [ ]:
# Dot product
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [ ]:
np.dot(x,y)

In [ ]:
# Scalar * Scalar
np.dot(5,6)

In [ ]:
# Scalar * Vector
x

In [ ]:
7*x

In [ ]:
# Vector * Vector
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [ ]:
np.dot(u,v)

In [ ]:
# Scalar * Matrix
A = np.array([[5,12,6],[-3,0,14]])
A

In [ ]:
4*A

In [ ]:
# Matrix * Matrix
B = np.array([[2,-1],[8,0],[3,0]])
B

In [ ]:
np.dot(A,B)

In [22]:
C = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
C

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [26]:
D = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
D

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [23]:
np.dot(C,D)

NameError: name 'D' is not defined

In [24]:
C.shape

(4, 5)

In [27]:
D.shape

(5, 2)